feat: include bridge port 10003, used in new devices in broadcast discovery, add token for future Runner S11 support
TomerFi/aioswitcher pull request #649
Opened 2023-04-13 23:10 UTC by YogevBokobza

## Description

> In newer firmware version of Runner S11, Runner S12, the broadcast port changed from 20003 to 10003. I added this port to the bridge discovery code.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [V] I have followed this repository's contributing guidelines.
- [V] I will adhere to the project's code of conduct.

## Additional information
This PR to support new Switcher Port and also prepare for Runner S11 support.

Switcher team is moving to Token based authentication.
I contact them and they give me the Token code for Python.
Need to implement this System as soon all thier devices will work only with Token.
 
> Anything else?

2023-04-14 04:56 UTC, TomerFi requested changes

2023-04-14 04:56 UTC, TomerFi commented on src/aioswitcher/api/tok.py
What is this file for?

2023-04-14 05:00 UTC, TomerFi commented
@YogevBokobza Thanks for you contribution.
Please take a look at my review comment.

@dmatik Do we know anything about another new port? 10003?

2023-04-14 06:36 UTC, dmatik commented
> @YogevBokobza Thanks for you contribution.
> 
> Please take a look at my review comment.
> 
> 
> 
> @dmatik Do we know anything about another new port? 10003?

Nope. At least first time I am hearing it. 
Still we need to check I believe. Right?

2023-04-14 06:43 UTC, TomerFi commented
> Still we need to check I believe. Right?

Defintally.

@YogevBokobza Can you please provide more information about the new port?

2023-04-14 06:44 UTC, TomerFi commented
> Switcher team is moving to Token based authentication.
> I contact them and they give me the Token code for Python.
> Need to implement this System as soon all thier devices will work only with Token.

@YogevBokobza If you can perhaps provide more details on this too. Is it related to the new port?

2023-04-14 10:27 UTC, YogevBokobza commented
I will explain better.
It all started when I recently bought a Runner S11 which is Runner and 2 Lights switches in the same module.
I tried using the Home Assistant integration for Switcher which uses this library and it failed.
My Runner S11 could not be found and worked.

I contacted the Switcher team to see what is changed.
They said there are 2 changes.

The first change is that the ports have been changed: 
- From 20002 To 10002 
- From 20003 To 10003
For their new devices. (could soon change old devices by an update)

The second change is that new devices (and soon old devices) need to authenticate with Token before able to communicate with them.
They say it's for security reasons.

So for Runner S11, S12, Lights and soon old devices will need each user of this integration to make him a Token and use this Token in the code for able to use the devices.
Anyone can get a token in this URL: https://switcher.co.il/GetKey

This tok.py code is given to me by Switcher Team as it contains their logic for the Token.
So I put this here as a preparation for my next step which is to add Runner S11 integration.

With this PR now I am able to find my Runner S11 in the Discovery, However, it is still not controlable.

By the way, I am able to integrate my Runner S11 to Home Assistant with a different approach.
There is a guy called Nitay who made Switcher integration to Homebridge.
So I am running Homebridge on VM using Virtualbox, Installed his Switcher Integration, and then using HomeKit Integration in Home Assistant.
THis is working perfectly and can offer temporary fix for devices that are not supported yet by this library such as Runner S11, Runner S12 and Lights.

His Homebridge integration: https://github.com/nitaybz/homebridge-switcher-platform
His integration is based on this JS library: https://github.com/nitaybz/switcher-js

I am now inspired by his library for able to adding S11 integration for this library.

Yogev.

2023-04-15 13:29 UTC, TomerFi requested changes

2023-04-15 13:29 UTC, TomerFi commented on src/aioswitcher/api/tok.py
Please remove this file, it doesn't look like it's being used.

2023-04-15 15:52 UTC, YogevBokobza commented
> I will explain better. It all started when I recently bought a Runner S11 which is Runner and 2 Lights switches in the same module. I tried using the Home Assistant integration for Switcher which uses this library and it failed. My Runner S11 could not be found and worked.
> 
> I contacted the Switcher team to see what is changed. They said there are 2 changes.
> 
> The first change is that the ports have been changed:
> 
> * From 20002 To 10002
> * From 20003 To 10003
>   For their new devices. (could soon change old devices by an update)
> 
> The second change is that new devices (and soon old devices) need to authenticate with Token before able to communicate with them. They say it's for security reasons.
> 
> So for Runner S11, S12, Lights and soon old devices will need each user of this integration to make him a Token and use this Token in the code for able to use the devices. Anyone can get a token in this URL: https://switcher.co.il/GetKey
> 
> This tok.py code is given to me by Switcher Team as it contains their logic for the Token. So I put this here as a preparation for my next step which is to add Runner S11 integration.
> 
> With this PR now I am able to find my Runner S11 in the Discovery, However, it is still not controllable.
> 
> By the way, I am able to integrate my Runner S11 into Home Assistant with a different approach. There is a guy called Nitay who made Switcher integration to Homebridge. So I am running Homebridge on VM using Virtualbox, Installing his Switcher Integration, and then using HomeKit Integration in Home Assistant. This is working perfectly and can offer a temporary fix for devices that are not supported yet by this library such as Runner S11, Runner S12 and Lights.
> 
> His Homebridge integration: https://github.com/nitaybz/homebridge-switcher-platform His integration is based on his JS library: https://github.com/nitaybz/switcher-js
> 
> I am now inspired by his library for being able to add S11 integration for this library.
> 
> Yogev.

@TomerFi  Please read this.

2023-04-16 05:07 UTC, TomerFi commented
> > I will explain better. It all started when I recently bought a Runner S11 which is Runner and 2 Lights switches in the same module. I tried using the Home Assistant integration for Switcher which uses this library and it failed. My Runner S11 could not be found and worked.
> > I contacted the Switcher team to see what is changed. They said there are 2 changes.
> > The first change is that the ports have been changed:
> > 
> > * From 20002 To 10002
> > * From 20003 To 10003
> >   For their new devices. (could soon change old devices by an update)
> > 
> > The second change is that new devices (and soon old devices) need to authenticate with Token before able to communicate with them. They say it's for security reasons.
> > So for Runner S11, S12, Lights and soon old devices will need each user of this integration to make him a Token and use this Token in the code for able to use the devices. Anyone can get a token in this URL: https://switcher.co.il/GetKey
> > This tok.py code is given to me by Switcher Team as it contains their logic for the Token. So I put this here as a preparation for my next step which is to add Runner S11 integration.
> > With this PR now I am able to find my Runner S11 in the Discovery, However, it is still not controllable.
> > By the way, I am able to integrate my Runner S11 into Home Assistant with a different approach. There is a guy called Nitay who made Switcher integration to Homebridge. So I am running Homebridge on VM using Virtualbox, Installing his Switcher Integration, and then using HomeKit Integration in Home Assistant. This is working perfectly and can offer a temporary fix for devices that are not supported yet by this library such as Runner S11, Runner S12 and Lights.
> > His Homebridge integration: https://github.com/nitaybz/homebridge-switcher-platform His integration is based on his JS library: https://github.com/nitaybz/switcher-js
> > I am now inspired by his library for being able to add S11 integration for this library.
> > Yogev.
> 
> @TomerFi @dmatik Please read this.

@YogevBokobza Please remove the unused tok.py file.
And please keep the concerns separated, this PR is port-related only, token-related goes in the other PR you mentioned.

2023-04-16 06:54 UTC, YogevBokobza commented
> > > I will explain better. It all started when I recently bought a Runner S11 which is Runner and 2 Lights switches in the same module. I tried using the Home Assistant integration for Switcher which uses this library and it failed. My Runner S11 could not be found and worked.
> > > I contacted the Switcher team to see what is changed. They said there are 2 changes.
> > > The first change is that the ports have been changed:
> > > 
> > > * From 20002 To 10002
> > > * From 20003 To 10003
> > >   For their new devices. (could soon change old devices by an update)
> > > 
> > > The second change is that new devices (and soon old devices) need to authenticate with Token before able to communicate with them. They say it's for security reasons.
> > > So for Runner S11, S12, Lights and soon old devices will need each user of this integration to make him a Token and use this Token in the code for able to use the devices. Anyone can get a token in this URL: https://switcher.co.il/GetKey
> > > This tok.py code is given to me by Switcher Team as it contains their logic for the Token. So I put this here as a preparation for my next step which is to add Runner S11 integration.
> > > With this PR now I am able to find my Runner S11 in the Discovery, However, it is still not controllable.
> > > By the way, I am able to integrate my Runner S11 into Home Assistant with a different approach. There is a guy called Nitay who made Switcher integration to Homebridge. So I am running Homebridge on VM using Virtualbox, Installing his Switcher Integration, and then using HomeKit Integration in Home Assistant. This is working perfectly and can offer a temporary fix for devices that are not supported yet by this library such as Runner S11, Runner S12 and Lights.
> > > His Homebridge integration: https://github.com/nitaybz/homebridge-switcher-platform His integration is based on his JS library: https://github.com/nitaybz/switcher-js
> > > I am now inspired by his library for being able to add S11 integration for this library.
> > > Yogev.
> > 
> > 
> > @TomerFi @dmatik Please read this.
> 
> @YogevBokobza Please remove the unused tok.py file. Also, let's keep the concerns separated, this PR is port-related only, token-related goes in the other PR you mentioned.

@TomerFi 
Done.

tok.py is deleted from this PR

2023-04-17 05:56 UTC, TomerFi commented
@YogevBokobza I appears that the CI failure is caused by _Codecov_ removing a deprecated package from _PyPi_.
Detail are [here](https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259).

I fixed it be removing the deprecated package from _pyproject.toml_: #651 (merged).

Please rebase this PR.

2023-04-17 19:24 UTC, YogevBokobza commented
> @YogevBokobza It appears that the CI failure is caused by _Codecov_ removing a deprecated package from _PyPi_. Details are [here](https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259).
> 
> I fixed it be removing the deprecated package from _pyproject.toml_: #651 (merged).
> 
> Please rebase this PR.

@TomerFi Rebase is done

2023-04-18 07:06 UTC, TomerFi approved these changes

2023-04-18 07:06 UTC, TomerFi submitted a review, later dismissed

2023-04-18 07:11 UTC, TomerFi commented
> > @YogevBokobza It appears that the CI failure is caused by _Codecov_ removing a deprecated package from _PyPi_. Details are [here](https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259).
> > I fixed it be removing the deprecated package from _pyproject.toml_: #651 (merged).
> > Please rebase this PR.
> 
> @TomerFi Rebase is done

Looks like a merge was done instead of a rebase.
Regardless, the CI wasn't triggered, maybe a GH issue, this needs a force push.

2023-04-18 07:32 UTC, TomerFi commented
Yep, merge instead of rebase:

![image](https://user-images.githubusercontent.com/28388442/232703422-b390b673-5ffb-4a3b-aae7-94fac0d594be.png)

I'll fix it manually myself, and if you'll need to keep working on this PR after, you'll have to force pull.
For future PRs, please refrain from using merge and stick to rebase.
And also, please avoid multiple concerns in a PR and keep commits counts to a minimum.

Thank you.

2023-04-18 07:42 UTC, TomerFi commented
> Yep, merge instead of rebase:
> 
> ![image](https://user-images.githubusercontent.com/28388442/232703422-b390b673-5ffb-4a3b-aae7-94fac0d594be.png)
> 
> I'll fix it manually myself, and if you'll need to keep working on this PR after, you'll have to force pull. For future PRs, please refrain from using merge and stick to rebase. And also, please avoid multiple concerns in a PR and keep commits counts to a minimum.
> 
> Thank you.

For future refs:
```
$ git reset --hard c0bbc43

$ git reset --soft 9d7ff9e

$ git commit -s -m "feat: include bridge port 10003 for type2 devices"

$ git rebase origin/dev
```

Of course the origin dev must be updated first (or an "upstream" remote).

2023-04-18 07:42 UTC, TomerFi approved these changes

2023-04-18 07:43 UTC, merged

2023-04-18 07:43 UTC, TomerFi commented
@all-contributors add @YogevBokobza for code