fix: solving block ssl in validate token
TomerFi/aioswitcher pull request #799
Opened 2024-08-13 22:21 UTC by YogevBokobza

## Description

> Describe what you did and why.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [ ] I have followed this repository's contributing guidelines.
- [ ] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

2024-08-13 22:22 UTC, YogevBokobza commented
This meant to fix [this](https://github.com/home-assistant/core/pull/123578#issuecomment-2287184038)

2024-08-13 22:28 UTC, YogevBokobza commented
I tested and looks like it's working.

2024-08-13 22:58 UTC, TomerFi approved these changes, later dismissed

2024-08-13 22:58 UTC, TomerFi commented
LGTM
Waiting for @thecode to have a look.

2024-08-25 09:00 UTC, YogevBokobza commented
@thecode I would be happy if you can review it

2024-08-25 18:28 UTC, thecode requested changes

2024-08-25 18:28 UTC, thecode commented on src/aioswitcher/device/tools.py
> +
Please move this inside the `validate_token`, I don't see any reason for making it a global variable

2024-08-26 10:09 UTC, YogevBokobza commented on src/aioswitcher/device/tools.py
> +
@thecode But the `validate_token` is an async function. Will not that result in the same issue I am trying to solve here?

2024-08-26 11:05 UTC, thecode commented on src/aioswitcher/device/tools.py
> +
https://github.com/home-assistant-libs/aiowebostv/blob/6f25f30e917d7d29d433ce03926b4571ff59b003/aiowebostv/webos_client.py#L131

An example inside an async method, it should work here also

2024-08-26 12:20 UTC, YogevBokobza commented on src/aioswitcher/device/tools.py
> +
Done.

2024-08-26 18:23 UTC, thecode commented on src/aioswitcher/device/tools.py
> +
Did you tested the change? I suggested to use `ssl_context = ssl.SSLContext()` and not `ssl.create_default_context()`

2024-08-27 05:33 UTC, YogevBokobza commented on src/aioswitcher/device/tools.py
> +
> Did you tested the change? I suggested to use `ssl_context = ssl.SSLContext()` and not `ssl.create_default_context()`

Yes I did test that and it worked, However, I changed that to what you requested.

2024-08-27 07:15 UTC, thecode approved these changes

2024-08-28 07:07 UTC, YogevBokobza commented
@TomerFi Please approve and merge :)

2024-08-28 20:43 UTC, TomerFi approved these changes

2024-08-28 20:43 UTC, merged

2024-08-28 20:43 UTC, TomerFi commented
@thecode @YogevBokobza You need a release?

2024-08-29 07:07 UTC, ybokobza commented
> @thecode @YogevBokobza Do we need to release?

Yes we need.. this is been used in HA. Thanks :)

2024-08-29 13:39 UTC, TomerFi commented
Release [4.0.3](https://github.com/TomerFi/aioswitcher/releases/tag/4.0.3).