feat: add shutter child lock support
TomerFi/aioswitcher pull request #811
Opened 2024-11-18 14:57 UTC by YogevBokobza

## Description

> Describe what you did and why.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [ ] I have followed this repository's contributing guidelines.
- [ ] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

2024-11-18 14:59 UTC, thecode commented
Can you separate the docs fixes from this PR? it looks strange to fix docs related from previous PRs together with a feature PR

2024-12-01 21:51 UTC, YogevBokobza commented
@thecode Don't know if you missed this PR or not.. please need your attention. whenever you can.
Thanks.

2024-12-03 19:59 UTC, thecode requested changes

2024-12-03 19:59 UTC, thecode commented on src/aioswitcher/device/__init__.py
> +        """Return the display name of the swing."""
```suggestion
        """Return the display name of the shutter child lock."""
```

2024-12-03 19:59 UTC, thecode commented on src/aioswitcher/device/__init__.py
> +        """Return the value of the swing."""
```suggestion
        """Return the value of the shutter child lock."""
```

2024-12-04 07:44 UTC, thecode approved these changes

2024-12-04 07:44 UTC, merged

2024-12-05 18:34 UTC, YogevBokobza commented
@TomerFi  Can you make a release, please?
I guess a minor is ok.
Thanks!

2024-12-05 21:23 UTC, TomerFi commented
Done: [5.1.0](https://github.com/TomerFi/aioswitcher/releases/tag/5.1.0).